package redis

const (
	REDIS_ID_LOCAL = 1 // 固定本区redis id 是1
	REDIS_ID_CROSS = 2 // 固定跨区redis id 是2
)

const (
	REDIS_ADMIN_ID      = REDIS_ID_LOCAL
	REDIS_USER_ID       = REDIS_ID_LOCAL
	REDIS_ONLINE_ID     = REDIS_ID_LOCAL
	REDIS_CHAT_ID       = REDIS_ID_LOCAL
	REDIS_GROUP_ID      = REDIS_ID_LOCAL
	REDIS_ITEM_ID       = REDIS_ID_LOCAL
	REDIS_MISSION_ID    = REDIS_ID_LOCAL
	REDIS_ACCOUNT_ID    = REDIS_ID_LOCAL
	REDIS_REDEEMCODE_ID = REDIS_ID_LOCAL // 兑换码
)
